const motivationalQuotes = [
    "It’s not about perfect. It’s about effort.",
    "Excellence is not a skill. It is an attitude.",
    "Focus on your goal. Don’t look in any direction but ahead.",
    "You don’t get what you wish for. You get what you work for.",
    "Do something now; your future self will thank you for later.",
    "Don’t try to be perfect. Just try to be better than you were yesterday.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Even the greatest were beginners. Don’t be afraid to take that first step.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "You can’t use up creativity. The more you use, the more you have.",
    "The best way to gain self-confidence is to do what you are afraid to do.",
    "If you hear a voice within you say ‘you cannot paint,’ then by all means paint, and that voice will be silenced.",
    "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying ‘I will try again tomorrow’.",
    "A little progress each day adds up to big results.",
    "It’s not about having time. It’s about making time.",
    "Losers quit when they’re tired. Winners quit when they’ve won.",
    "Skill is only developed by hours and hours of work.",
    "You will never always be motivated. You have to learn to be disciplined.",
    "Self-discipline is the magic power that makes you virtually unstoppable.",
    "The way to get started is to quit talking and begin doing.",
    "Focus on doing the right things instead of a bunch of things.",
    "The successful warrior is the average man, with laser-like focus.",
    "Discipline is just choosing between what you want now and what you want most.",
]

export default motivationalQuotes